modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/SilentChaos512/Silents-Mechanisms/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms"
logoFile="logo.png"
credits="Code by Silent, concept and textures by geddy135"
authors="SilentChaos512"

[[mods]]
    modId="silents_mechanisms"
    version="${file.jarVersion}"
    displayName="Silent's Mechanisms"
    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/Silents-Mechanisms/1.14/update.json"
    description='''
    Simple machines and energy-generating blocks
    '''

[[dependencies.silents_mechanisms]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silents_mechanisms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgear]]
    modId="silentlib"
    mandatory=true
    versionRange="[4,)"
    ordering="NONE"
    side="BOTH"
